
GET http://localhost:3000/api/cars

###

GET http://localhost:3000/api/cars/:Id

###


POST http://localhost:3000/api/cars/
Content-Type: application/json

{
        "Modell":"NewaaaastCar",
        "Id":"",
        "color":"NewcarColor",
        "price":"We'll see"
}

###

PUT http://localhost:3000/api/cars/2
Content-Type: application/json

{
        "Modell" : "NewCar",
        "color" : "NewcarColor",
        "price" : "We'll see"
}

###

DELETE http://localhost:3000/api/cars/2

